#
# (C) Copyright 2022 Larry Milne (https://www.larrycloud.ca)
#
# This code is distributed on "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# @author: qawse3dr a.k.a Larry Milne
#

image: gcc:latest

stages:          # List of stages for jobs, and their order of execution
  - test
  - build



test:       # This job runs in the build stage, which runs first.
  stage: test
  before_script:
    - apt-get -qq update && apt-get -f -qq install cmake googletest libgtest-dev || true
  script:
    - mkdir build
    - cd build
    - cmake -DPICOLATOR_TEST=1 -DCOVERAGE=1 ..
    - make
    - ./test/picolator_test

build:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - apt-get -qq update && apt-get -f -qq install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libstdc++-arm-none-eabi-newlib || true
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/picolator.uf2
    expire_in: 1 week
